version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app

  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/vue:/app
    stdin_open: true
    tty: true